stages:
  train:
    cmd: python src/train.py
    deps:
    - data/FER2013
    - src/train.py
    params:
    - train.batch_size
    - train.decay
    - train.learning_rate
    - train.n_epoch
    - train.seed
    outs:
    - model/emotion_model.h5
    - model/emotion_model.json
  evaluation:
    cmd: python src/evaluation.py
    deps:
    - data/FER2013
    - model/emotion_model.h5
    - model/emotion_model.json
    params:
    - test.seed
